/**
 * Generates a USER.md configuration file for the TAPN agent ecosystem.
 * This file is consumed by all agents (Scout, Taylor, Echo, Hermes, Aria)
 * to understand the user's profile, preferences, and constraints.
 */
export function generateUserMd(profile) {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const list = (arr) =>
    (arr || []).length > 0
      ? arr.map((item) => `- ${item}`).join('\n')
      : '- (none specified)';

  const val = (v) => v || '—';

  return `# USER.md — ${val(profile.fullName)}

> Agent ecosystem configuration for TAPN
> Generated ${date}

---

## Identity

**Full Name:** ${val(profile.fullName)}
**Email:** ${val(profile.email)}
**Phone:** ${val(profile.phone)}
**Location:** ${val(profile.location)}
**LinkedIn:** ${val(profile.linkedinUrl)}
**Portfolio:** ${val(profile.portfolioUrl)}

---

## Career Goals

**Current Title:** ${val(profile.currentTitle)}
**Years of Experience:** ${val(profile.yearsExperience)}

**Target Roles:**
${list(profile.targetRoles)}

**Target Industries:**
${list(profile.targetIndustries)}

**Professional Summary:**
${profile.bio || '(No summary provided)'}

---

## Background

**Technical Skills:** ${(profile.technicalSkills || []).join(', ') || '—'}

**Top Strengths:**
${list(profile.topStrengths)}

**Education:** ${val(profile.educationDegree)} in ${val(profile.educationField)} — ${val(profile.educationSchool)} (${val(profile.educationYear)})

**Work Authorization:** ${val(profile.workAuthorization)}

---

## Application Preferences

**Work Type:** ${val(profile.workTypePreference)}
**Minimum Salary:** ${val(profile.minSalary)}
**Company Size Preference:** ${val(profile.companySize)}

**Must-Have Criteria:**
${list(profile.mustHaveCriteria)}

**Deal-Breaker Keywords:**
${list(profile.dealBreakerKeywords)}

**Blacklisted Companies:**
${list(profile.blacklistedCompanies)}

---

## Scheduling Constraints

**Available Hours:** ${val(profile.availableHours)}
**Timezone:** ${val(profile.timezone)}
**Minimum Notice:** 48 hours
**Interview Gap:** 1 hour minimum between interviews

---

## Communication Style

**Preferred Style:** ${val(profile.communicationStyle)}

---

*Generated by TAPN on ${date}*
`;
}
