import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { supabase } from "../../lib/supabase";

export default function ResumesView({ applications, timeAgo, userId }) {
  const [resumeLogs, setResumeLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedResume, setSelectedResume] = useState(null);

  useEffect(() => {
    if (!supabase || !userId) {
      setLoading(false);
      return;
    }

    supabase
      .from("agent_logs")
      .select("*")
      .eq("user_id", userId)
      .eq("agent_name", "taylor")
      .eq("action", "resume_tailored")
      .order("created_at", { ascending: false })
      .limit(50)
      .then(({ data, error }) => {
        if (!error && data) setResumeLogs(data);
        setLoading(false);
      });

    const channel = supabase
      .channel("resume-logs")
      .on(
        "postgres_changes",
        {
          event: "INSERT",
          schema: "public",
          table: "agent_logs",
          filter: "agent_name=eq.taylor",
        },
        (payload) => {
          if (payload.new?.user_id !== userId) return;
          if (payload.new.action === "resume_tailored") {
            setResumeLogs((prev) => [payload.new, ...prev]);
          }
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [userId]);

  // Merge resume logs with application data
  const resumeItems = resumeLogs.map((log) => {
    const details = log.details || {};
    const matchedApp = applications.find(
      (a) =>
        a.company_name?.toLowerCase() === details.company?.toLowerCase() &&
        a.job_title?.toLowerCase() === details.job_title?.toLowerCase()
    );
    return {
      ...log,
      company: details.company || "unknown",
      jobTitle: details.job_title || "unknown",
      resumePath: details.resume_path || null,
      keywordsMatched: details.keywords_matched_count || 0,
      tier1Coverage: details.tier1_coverage || null,
      applicationStatus: matchedApp?.status || null,
    };
  });

  return (
    <>
      {/* Header */}
      <motion.div
        className="view-header"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <div>
          <h1 className="view-title">resumes</h1>
          <p className="view-subtitle">
            {resumeItems.length} tailored resumes generated by taylor
          </p>
        </div>
        <div className="resume-stats-row">
          <div className="mini-stat">
            <span className="mini-stat-value">{resumeItems.length}</span>
            <span className="mini-stat-label">generated</span>
          </div>
          <div className="mini-stat">
            <span className="mini-stat-value">
              {resumeItems.filter((r) => r.keywordsMatched > 10).length}
            </span>
            <span className="mini-stat-label">high match</span>
          </div>
        </div>
      </motion.div>

      {/* Resume Grid */}
      <motion.div
        className="resumes-grid"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.1 }}
      >
        {loading ? (
          <div className="panel-loading">
            <span className="loading-dot" /> loading...
          </div>
        ) : resumeItems.length === 0 ? (
          <div className="activity-empty resume-empty">
            <span className="activity-empty-icon">◇</span>
            <p>no resumes generated yet.</p>
            <p className="empty-hint">
              taylor creates ats-optimized resumes when the pipeline runs.
              each resume is tailored to the specific job description.
            </p>
          </div>
        ) : (
          resumeItems.map((resume, i) => (
            <motion.div
              key={resume.id}
              className={`resume-card ${selectedResume?.id === resume.id ? "selected" : ""}`}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.3, delay: i * 0.04 }}
              onClick={() =>
                setSelectedResume(selectedResume?.id === resume.id ? null : resume)
              }
            >
              <div className="resume-card-top">
                <span className="resume-icon">◇</span>
                {resume.applicationStatus && (
                  <span className={`app-status-badge ${resume.applicationStatus}`}>
                    {resume.applicationStatus?.replace(/_/g, " ")}
                  </span>
                )}
              </div>
              <h3 className="resume-company">{resume.company}</h3>
              <span className="resume-role">{resume.jobTitle}</span>

              <div className="resume-metrics">
                <div className="resume-metric">
                  <span className="metric-value">{resume.keywordsMatched}</span>
                  <span className="metric-label">keywords</span>
                </div>
                {resume.tier1Coverage && (
                  <div className="resume-metric">
                    <span className="metric-value">{resume.tier1Coverage}%</span>
                    <span className="metric-label">tier 1 coverage</span>
                  </div>
                )}
              </div>

              <div className="resume-card-footer">
                <span className="resume-date">{timeAgo(resume.created_at)}</span>
                {resume.resumePath && (
                  <span className="resume-path-indicator">pdf available</span>
                )}
              </div>
            </motion.div>
          ))
        )}
      </motion.div>

      {/* Selected Resume Detail */}
      <AnimatePresence>
        {selectedResume && (
          <motion.div
            className="app-detail-panel"
            initial={{ opacity: 0, y: 20, height: 0 }}
            animate={{ opacity: 1, y: 0, height: "auto" }}
            exit={{ opacity: 0, y: -10, height: 0 }}
            transition={{ duration: 0.3 }}
          >
            <div className="detail-header">
              <div>
                <h3 className="detail-company">{selectedResume.company}</h3>
                <span className="detail-role">{selectedResume.jobTitle}</span>
              </div>
              <button className="detail-close" onClick={() => setSelectedResume(null)}>
                ✕
              </button>
            </div>
            <div className="detail-grid">
              <div className="detail-item">
                <span className="detail-label">keywords matched</span>
                <span className="detail-value">{selectedResume.keywordsMatched}</span>
              </div>
              <div className="detail-item">
                <span className="detail-label">tier 1 coverage</span>
                <span className="detail-value">
                  {selectedResume.tier1Coverage ? `${selectedResume.tier1Coverage}%` : "—"}
                </span>
              </div>
              <div className="detail-item">
                <span className="detail-label">generated</span>
                <span className="detail-value">
                  {new Date(selectedResume.created_at).toLocaleString()}
                </span>
              </div>
              <div className="detail-item">
                <span className="detail-label">file path</span>
                <span className="detail-value mono">
                  {selectedResume.resumePath || "not saved"}
                </span>
              </div>
            </div>
            {selectedResume.details && Object.keys(selectedResume.details).length > 0 && (
              <div className="detail-jd">
                <span className="detail-label">full metadata</span>
                <pre className="detail-jd-text">
                  {JSON.stringify(selectedResume.details, null, 2)}
                </pre>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}
